### ISSUE TITLE
Allow most ganache options to be passed through colony service

### ISSUE THREAD

**Issue by bmiller59** [JoinColony/colonyStarter#101]
## Description

Allow colony service to pass most command line arguments to ganache when `colony service start-ganache` is run.

## Rationale

It would be helpful to be able to pass most options to ganache through colony service, for example to set a higher initial ETH value. Or to set handling of VM errors. If possible, default options could be set but overridable when the command line argument was passed. 

I understand that some options are critical to the operation of colonyNetwork, for example the specified addresses to use. Either these essential options would not be overridable, or a warning could be provided by colony service when such options were overriden.

**Comment by ryanchristo** [comment]
Thanks @bmiller59! I like the idea of having default options that can be overridden.
