### ISSUE TITLE
Contract starter: Automatically place important colony contract addresses in a config file

### ISSUE THREAD

**Issue by bmiller59** [JoinColony/colonyStarter#102]
## Description

When colony service is used, for example with the contract starter, automatically place the address of deployed Colony contracts (e.g. EtherRouter) in a config file so that they can be easily looked up and used in contract development that leverages base colony network contracts. Also document these addresses and their purposes.

## Rationale

In the current version of the contract starter, you can find this comment in the contract migration:

```
// The address of the first colony created with `yarn colony-setup`
const colonyAddress = "0xEc46E0d7208FF021CDb5B9D47196adb8bbe07a3D";
```

Having to look up the deployed colony address and insert it manually into the migration is something I have been doing as well when extending the colony contracts, but it would be  helpful if this process could be automated. Perhaps on deployment of the colony contracts the address could be written to a config file e.g. colony-config.js in the root of the project, so that it could be opened and read by the migrations. That config file could store the address of the ColonyNetwork contracts for each network to which it is deployed. (The Mainnet and Rinkeby official deployments could also be hard coded there for reference since users will not be deploying those themselves generally.)

This is a configuration file approach currently used by the ZeppelinOS [zos cli](https://docs.zeppelinos.org/docs/configuration.html).

**Comment by ryanchristo** [comment]
@bmiller59 Thanks again! The example really helps. I think this would be a great improvement.
