### ISSUE TITLE
path error with `yarn colony-setup` in colony-example-angular (and maybe elsewhere)

### ISSUE THREAD

**Issue by fuguefoundation** [JoinColony/colonyStarter#109]
https://github.com/JoinColony/colonyStarter/edit/master/docs/_Examples_ColonyExampleAngular.md

Package.json has under "scripts" section:

`"colony-setup": "node scripts/colonySetup.js",`

should be:

`"colony-setup": "node node_modules/@colony/colony-cli/src/scripts/colonySetup.js",`

**Comment by ryanchristo** [comment]
@fuguefoundation Thanks for pointing this out! Looks like I missed one while updating the packages. As you can see in the `colony-starter-angular` package, the `colony-setup` script is now included in the `colony-cli` package as a service command, so it should look like this:

```
"colony-setup": "colony service colony-setup",
```

I'll get this fixed and publish a new release of this package. Thanks again!

**Comment by ryanchristo** [comment]
Actually, I just realized this script was not intended to be included in the example packages, which is probably why it got overlooked. I am removing it from the scripts and documentation in #110.

The `colony-setup` script is a simple script used to create a test token and colony, which is users can do using the UI in the angular example, so no need to include it.
