### ISSUE TITLE
Unable to compile core-js in colony-example-vue

### ISSUE THREAD

**Issue by matt-roe** [JoinColony/colonyStarter#118]
## Description

_Write a detailed description of the issue/feature/question._

Trying basic setup of colony-example-vue

```
matt@Matt-buntu:~/colony-example-vue/colony-example-vue$ sudo yarn serve
yarn run v1.17.3
$ vue-cli-service serve
 INFO  Starting development server...
10% building 2/2 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/matt/colony-example-vue/colony-example-vue/public
ℹ ｢wds｣: 404s will fallback to /index.html
98% after emitting CopyPlugin

 ERROR  Failed to compile with 47 errors                             11:25:32 PM

These dependencies were not found:

* core-js/modules/es6.number.constructor in ./src/api/funding.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/colony/funding/Claim.vue?vue&type=script&lang=js&
* core-js/modules/es6.object.keys in ./src/api/task.js, ./src/api/skills.js and 9 others
* core-js/modules/es6.regexp.to-string in ./src/helpers/ecp.js
* core-js/modules/es6.string.iterator in ./src/api/domain.js, ./src/api/task.js and 3 others
* core-js/modules/es6.string.sub in ./src/api/funding.js
* core-js/modules/es7.object.entries in ./src/api/accounts.js
* core-js/modules/es7.object.get-own-property-descriptors in ./src/api/task.js, ./src/api/skills.js and 9 others
* core-js/modules/web.dom.iterable in ./src/api/domain.js, ./src/api/accounts.js and 13 others

To install them, you can run: npm install --save core-js/modules/es6.number.constructor core-js/modules/es6.object.keys core-js/modules/es6.regexp.to-string core-js/modules/es6.string.iterator core-js/modules/es6.string.sub core-js/modules/es7.object.entries core-js/modules/es7.object.get-own-property-descriptors core-js/modules/web.dom.iterable
```
## Steps to Reproduce

_If you are reporting a bug, list the steps you took that led to the issue._

Followed install steps for colony-example-vue on ubuntu 18.04

Remediation:

https://stackoverflow.com/questions/55308769/module-not-found-error-cant-resolve-core-js-es6
```
yarn add core-js@2.5.7
```
```
matt@Matt-buntu:~/colony-example-vue/colony-example-vue$ sudo yarn serve
yarn run v1.17.3
$ vue-cli-service serve
 INFO  Starting development server...
10% building 2/2 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/matt/colony-example-vue/colony-example-vue/public
ℹ ｢wds｣: 404s will fallback to /index.html
98% after emitting CopyPlugin

 WARNING  Compiled with 1 warnings                                   11:37:56 PM

 warning  in ./node_modules/web3-eth-accounts/src/scrypt.js

Critical dependency: the request of a dependency is an expression


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.77.111.39:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.
```

**Comment by matt-roe** [comment]
This was with colony-example-vue

**Comment by ryanchristo** [comment]
Hi @matt-roe! Can you update the issue so that it includes more information about what your are attempting to do? Also, can you please use blocks?

What do you mean when you say "Followed install steps on ubuntu 18.04"? Are you attempting to run the `colony-example-vue` package on a virtual machine? Have you tried running `colony-example-vue` locally? I'm also a bit confused why you are running yarn commands with `sudo` and this might be related to the issue that you are experiencing.

**Comment by matt-roe** [comment]
I was setting up colony-example-vue locally on ubuntu. Following the instructions I set things up with docker.

Sudo probably wasn’t necessary there, tried things both ways when troubleshooting. Essentially, it is fixed with that lower version of core-js so I think you just need to update the dependencies to that older version, or maybe you can add some packages I was seeing as potential solutions. It seemed like a change to core-js in version 3. 

Sorry about that, I will put things in blocks next time.

Matt Roe

**Comment by ryanchristo** [comment]
> Sorry about that, I will put things in blocks next time

No problem! You can also edit the issue description.

> maybe you can add some packages I was seeing as potential solutions

What packages were you seeing as potential solutions?

Also, feel free to open a PR that sets `core-js` to `2.6.9` rather than `^3.1.4`. It looks likes the issue is might be a breaking change in version 3.

**Comment by matt-roe** [comment]
https://github.com/vuejs/vue-cli/issues/3678

I will attempt a PR
