### ISSUE TITLE
Update colony-starter-react package

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/colonyStarter#16]
## Description

~Create a `colony-starter-uport` package that will demonstrate how to integrate uPort with colonyJS.~

Update `colony-starter-react` package to be a true boilerplate.

**Comment by pynchmeister** [comment]
Is this still open? I would be glad to give it a shot!

**Comment by ryanchristo** [comment]
Yes, still open!

I was considering an alternative direction since we will need to create a front-end example dApp that connects to uPort, so maybe something built on top of another package. My thought was to split the react package into a simplified package and the more robust package that currently exists, then we could demonstrate a uPort integration on top of the basic package. I am open to ideas though.

What do you think? If you were to take on the issue as is, how would you build it?

**Comment by pynchmeister** [comment]
I think simplification is almost always a good idea although I have yet to see the current react package visually given to some compilation errors.

I was planning to model the issue after this truffle-box: https://github.com/truffle-box/react-uport-box

This is the only time I have used uPort, so I am a bit biased, although always open to suggestion/guidance!

**Comment by ryanchristo** [comment]
I would be happy to help with suggestions and guidance!

I think the simplified package will need to be more in line with create-react-app, which I believe is what all truffle boxes currently use. We will not need truffle in the starter package because we will be using colonyNetwork as a submodule but I think the `react-uport-box` would be a good point of reference.

Would you be interested in creating a simplified `colony-starter-react` package from scratch using `create-react-app` and then coming back to this and adding a uPort integration?

**Comment by pynchmeister** [comment]
Sure, I would be down to give it a try!
