### ISSUE TITLE
colony-js-adapter-ethers throws error with latest yarn

### ISSUE THREAD

**Issue by igorline** [JoinColony/colonyStarter#45]
I'm getting this error with `@colony/colony-starter-basic@1.0.0-beta.6`

`error @colony/colony-js-adapter-ethers@1.7.0: The engine "yarn" is incompatible with this module. Expected version ">=1.3.2".
error Found incompatible module`

I'm using yarn 1.12.3

**Comment by ryanchristo** [comment]
As mentioned in the Gitter channel, I was unable to reproduce using node `10.12` and yarn `1.12.3`. I created a PR to add the recommended yarn version to the docs. Let me know if a fresh setup works.

**Comment by chmanie** [comment]
We really need to remove that line from colony-js. Pinging @JamesLefrere

**Comment by JamesLefrere** [comment]
Fixed in colonyJS#316 👍 We'll make a new release so this can be resolved here.

**Comment by igorline** [comment]
My bad! Seems like yarn wasn't linked to proper node version in nvm, thus there was this error thrown while setting up new project.
After installing -> linking yarn to proper node version everything is working smoothly!

**Comment by ryanchristo** [comment]
@igorline No problem! Glad to hear everything is working now.
