### ISSUE TITLE
Add UI components to colony-starter-angular

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/colonyStarter#59]
## Description

Currently, the `colony-starter-angular` package runs through the following 6 examples:

1. `connectNetwork`
2. `createToken`
3. `createColony`
4. `getColonyClient`
5. `addDomain`
6. `createTask`

As a user, I would like to perform these actions via a simple user interface, i.e. when creating a token, I would like to be able to enter the name and symbol using a form with a submit button.

**Comment by fuguefoundation** [comment]
Great, will address in the coming days.

**Comment by fuguefoundation** [comment]
@ryanchristo [PR submitted](https://github.com/JoinColony/colonyStarter/pull/60)

**Comment by ryanchristo** [comment]
@fuguefoundation Awesome! Thanks again. I'll take a look at the PR and update the README once the package has been published (when it is possible to call `colony-starter colony-starter-angular`).

**Comment by ryanchristo** [comment]
@fuguefoundation Thanks again! Nice work!
