### ISSUE TITLE
Errors when running scripts/start_ganache.sh

### ISSUE THREAD

**Issue by pynchmeister** [JoinColony/colonyStarter#73]
## Description

I was curious to discover the intricacies of the colony ecosystem, although I have an issue activating colony-starter-basic...

## Steps to Reproduce

I followed the directions in the root readme of this repository for installation via yarn. The error arose when running the ```yarn start-ganache``` command.

As follows are the error messages generated:

``` yvm exec 1.12.3 start-ganache
yarn run v1.12.3
$ sh scripts/start_ganache.sh
scripts/start_ganache.sh: line 4: cd: lib/colonyNetwork: No such file or directory
scripts/start_ganache.sh: line 7: ganache-cli: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: /Users/harrislevine/.yvm/versions/v1.12.3/bin/yarn.js start-ganache
yarn failed, non-zero exit
```

**Comment by ryanchristo** [comment]
Hi @pynchmeister! Thanks for posting an issue.

I'm unable to reproduce the error. It looks like `colonyNetwork` was not added as a submodule, which is why you are receiving the `lib/colonyNetwork: No such file or directory` error. This should have been added when running `colony-starter colony-starter-basic`.

I was able to run the following commands without error:

```
yarn global add colony-starter

colony-starter colony-starter-basic

cd colony-starter-basic

yarn start-ganache
```

Did you run into any errors when running the `colony-starter colony-starter-basic` command?

**Comment by pynchmeister** [comment]
Hello @ryanchristo! Thank you for the quick response. I can't seem to get past the first command, ```yarn global add colony-starter```, which produces the error seen below:

```yarn global v1.13.0
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/colony-starter: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/harrislevine/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

I reinstalled yarn globally using npm, I am using yarn v1.13.0. I tried using search engines to discover the place where the yarn package is located, but with no luck (I am not a yarn expert, myself)

**Comment by ryanchristo** [comment]
Whoops! Amended my comment above. The proper name for the package includes `@colony/` as it appears in the README:

```
yarn global add @colony/colony-starter
```

**Comment by pynchmeister** [comment]
Awesome, that downloaded fine with the inclusion of the @ sign. Unfortunately the second command does not work successfully: 

```colony-starter colony-starter-basic```

```zsh: command not found: colony-starter```

**Comment by ryanchristo** [comment]
Any chance you're using Linux?

If so, you'll need to go through the [Linux Setup](https://github.com/JoinColony/colonyStarter/blob/master/.github/LINUX_SETUP.md) instructions.

**Comment by pynchmeister** [comment]
Yes, I am on macOS. Thanks for the link, I will close this issue once I get this repo up and running 🐲

**Comment by pynchmeister** [comment]
Alright I have run into more issues, although I have finally gotten ```yarn start-ganache
``` to run without errors. I will open a new issue...
