### ISSUE TITLE
Error: Command failed: yarn initialize

### ISSUE THREAD

**Issue by bmiller59** [JoinColony/colonyStarter#82]
## Description

Error: Command failed: yarn initialize when using colony-starter

## Steps to Reproduce

After running `npm install -g colony-starter` to upgrade colony-starter and then running ` colony-starter colony-starter-basic` I get the following error.

```
$ colony-starter colony-starter-basic

  Verifying yarn is installed...

  Creating colony-starter-basic folder...

  Preparing to install @colony/colony-starter-basic...

  Installing @colony/colony-starter-basic...

yarn install v1.13.0
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning ipfs > ipfs-api@22.3.0: ipfs-api has been renamed to ipfs-http-client, please update your package.json to get the latest version.
warning ipfs > hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.
warning ipfs > joi > hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.
warning ipfs > hapi > heavy > joi@10.6.0: This version is no longer maintained. Please upgrade to the latest version.
warning ipfs > hapi > podium > joi@10.6.0: This version is no longer maintained. Please upgrade to the latest version.
warning ipfs > hapi > shot > joi@10.6.0: This version is no longer maintained. Please upgrade to the latest version.
warning ipfs > hapi > catbox > joi@10.6.0: This version is no longer maintained. Please upgrade to the latest version.
warning ipfs > libp2p-webrtc-star > inert > joi@10.6.0: This version is no longer maintained. Please upgrade to the latest version.
warning ipfs > ipld > ipld-ethereum > ethereumjs-block > merkle-patricia-tree > level-ws > xtend > object-keys@0.4.0:
warning jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 50.97s.

  Initializing colony-starter-basic...

yarn run v1.13.0
error Command "initialize" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

  Aborting installation. Please report an issue.

  Error: Command failed: yarn initialize
```

**Comment by ryanchristo** [comment]
Hmmm... based off the error message it looks like an issue with calling `yarn initialize`, which I am not sure why that would be called. Did you at one point have a script file in your project named `initialize` that no longer exists? Did you try globally installing with `yarn`? I am using the same version of `yarn` and I was unable to reproduce the error.

Also, have you tried upgrading to the latest `colony-starter` package? Another update is coming soon so things will change again but the current instructions on the [master](https://github.com/JoinColony/colonyStarter/tree/master) branch represent the latest published packages. I would recommend updating the globally installed `colony-starter` package or waiting for the `colony-cli` package to be published (we are switching up the names a bit in preparation to build out more commands for what will be `colony-cli` - inspired by your feature request).

**Comment by bmiller59** [comment]
Thanks, Ryan. I had `rm -rf colony-starter-basic` and then ran `colony-starter colony-starter-basic` as described above, so it should have been a clean install. And no, I had not set up an initialize script. Strange. Anyway, I do not need colony-starter right now: I had only tried to pull it down to compare to see what changed when trying to debug other issues. Feel free to close this for now and I will try again when colony-cli is ready. Thanks.
