### ISSUE TITLE
Feature: Allow ganache to be started without --noVMErrorsOnRPCResponse

### ISSUE THREAD

**Issue by bmiller59** [JoinColony/colonyStarter#88]
## Description

It should be possible to start the ganache service through `colony-cli` without the `--noVMErrorsOnRPCResponse` option.

## Recommendation

Please remove `--noVMErrorsOnRPCResponse` as a required option when starting ganache because many developers who use truffle to develop their contracts will want to be able access revert reasons, and with this setting they cannot. (See this issue for more information: https://github.com/trufflesuite/ganache-cli/issues/540)

If any developers do want to use this option, they can pass it when they run `yarn start-ganache`.

Thank you.

**Comment by ryanchristo** [comment]
Consider it done! I will get this fixed and publish a new release early next week.

**Comment by ryanchristo** [comment]
@bmiller59 Just published a new release with `--noVMErrorsOnRPCResponse` not included by default and the option to add it. Thanks again.
