### ISSUE TITLE
Infinite loop when installing @colony/colony-cli

### ISSUE THREAD

**Issue by luzzif** [JoinColony/colonyStarter#92]
On Mac, both with `npm` and `yarn` (as expected) I get stuck in an infinite loop when trying to globally (or locally) install `@colony/colony-cli`.

I think the `postinstall` script has to do with it.

Here's a log extract:

```
> @colony/colony-cli@1.0.0-beta.2 postinstall /Users/luzzif/.nvm/versions/node/v10.15.1/lib/node_modules/@colony/colony-cli
> sh scripts/postinstall.sh

0.4.23: Pulling from ethereum/solc
Digest: sha256:b9895a3b676cc605247a77b3ac8e4f3aa0cf64ebbf563d82ecf726c2d9a005bc
Status: Image is up to date for ethereum/solc:0.4.23
Cloning into 'colonyNetwork'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
scripts/postinstall.sh: line 26: cd: colonyNetwork: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
yarn install v1.12.3
warning ../../../../../../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.15.2", while you're on "1.12.3".
info To upgrade, run the following command:
$ brew upgrade yarn
$ sh scripts/postinstall.sh
0.4.23: Pulling from ethereum/solc
Digest: sha256:b9895a3b676cc605247a77b3ac8e4f3aa0cf64ebbf563d82ecf726c2d9a005bc
Status: Image is up to date for ethereum/solc:0.4.23
mkdir: lib: File exists
Cloning into 'colonyNetwork'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
scripts/postinstall.sh: line 26: cd: colonyNetwork: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
yarn install v1.12.3
warning ../../../../../../../../package.json: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ sh scripts/postinstall.sh
0.4.23: Pulling from ethereum/solc
Digest: sha256:b9895a3b676cc605247a77b3ac8e4f3aa0cf64ebbf563d82ecf726c2d9a005bc
Status: Image is up to date for ethereum/solc:0.4.23
mkdir: lib: File exists
Cloning into 'colonyNetwork'...
```

I'm looking forward to trying colony, but this is not exactly the best thing to first see from it.

**Comment by ryanchristo** [comment]
Hey @luzzif. Thank you for opening an issue.

```
Cloning into 'colonyNetwork'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

It looks like you might not have `ssh` installed and one of the colonyNetwork submodules is currently using ssh. [See here](https://github.com/JoinColony/colonyToken/blob/2dc3136d71c0af9adb9b05e187885dd9dcae94c8/.gitmodules#L3). Using `ssh` is a good best practice but we need to switch this to `https` or make it more clear that `ssh` is required. Here are some [instructions for setting up ssh](https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account).

An exit in the script should be added if it fails to clone the colonyNetwork repository. I created the cli service commands last week and this particular project is still in beta, so I appreciate you taking the time to open an issue and sorry for a frustrating first experience.

I'll keep this issue open until this is addressed in the cli package.

**Comment by luzzif** [comment]
Adding a freshly-generated SSH key to GitHub solved the problem.
Anyway, clearing things up about the required SSH setup should help newcomers to get smoothly introduced to Colony in the future.
Thanks for the fast and thorough feedback though!
